#!/usr/bin/env bash
# autonomOS installer.
#
# Usage:
#   curl -fsSL https://autonomos.dev/install.sh | bash
#
# Environment variables (for advanced / hermetic-test invocation):
#   INSTALL_PREFIX        Install root (default: $HOME/.local)
#   BUNDLE_URL            Where to fetch release artifacts from
#                         (default: https://github.com/aterrylu/autonomOS/releases/latest/download)
#   SKIP_INSTALL_SERVICE  Skip running `autonomos install-service` post-install (test/CI)
#   SKIP_NODE_CHECK       Skip the node-version check (test/CI; the bundle still needs node)
#
# What it does:
#   1. Detect OS+arch via uname
#   2. Require node >= 20 (the bundle is a Node-runtime JS bundle, not a static binary)
#   3. Download autonomos-<platform>.tar.gz from the release
#   4. Verify SHA256 against SHA256SUMS in the same release
#   5. Extract to $INSTALL_PREFIX/share/autonomos/
#   6. Write a wrapper at $INSTALL_PREFIX/bin/autonomos that execs node + the bundle
#   7. Optionally run `autonomos install-service` to set up the OS-native daemon

set -euo pipefail

INSTALL_PREFIX="${INSTALL_PREFIX:-$HOME/.local}"
BUNDLE_URL="${BUNDLE_URL:-https://github.com/aterrylu/autonomOS/releases/latest/download}"

# ── platform detection ────────────────────────────────────────────────────
case "$(uname -s)/$(uname -m)" in
  Darwin/arm64)   PLATFORM=darwin-arm64 ;;
  Darwin/x86_64)  PLATFORM=darwin-x64 ;;
  Linux/x86_64)   PLATFORM=linux-x64 ;;
  Linux/aarch64)  PLATFORM=linux-arm64 ;;
  *)
    echo "Unsupported platform: $(uname -s)/$(uname -m)" >&2
    exit 1
    ;;
esac
echo "[install] Detected platform: $PLATFORM"

# ── node version check ────────────────────────────────────────────────────
if [[ "${SKIP_NODE_CHECK:-0}" != "1" ]]; then
  if ! command -v node >/dev/null 2>&1; then
    cat >&2 <<'EOF'
Error: Node.js is required.

The autonomOS bundle is a Node-runtime JS application (the static-binary path
is blocked on a Bun/node-pty ABI issue, tracked separately). Install Node 20+
via your package manager:

  macOS:    brew install node
  Linux:    https://nodejs.org/en/download/package-manager
EOF
    exit 1
  fi
  NODE_MAJOR=$(node -e 'console.log(process.versions.node.split(".")[0])')
  if [[ "$NODE_MAJOR" -lt 20 ]]; then
    echo "Error: node 20+ required (found $(node --version))" >&2
    exit 1
  fi
fi

# ── download ──────────────────────────────────────────────────────────────
TARBALL="autonomos-${PLATFORM}.tar.gz"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

echo "[install] Downloading ${BUNDLE_URL}/${TARBALL}..."
curl -fsSL -o "$TMP/$TARBALL" "${BUNDLE_URL}/${TARBALL}"

echo "[install] Downloading SHA256SUMS..."
curl -fsSL -o "$TMP/SHA256SUMS" "${BUNDLE_URL}/SHA256SUMS"

# ── checksum verification ─────────────────────────────────────────────────
echo "[install] Verifying SHA256..."
EXPECTED=$(grep " ${TARBALL}\$" "$TMP/SHA256SUMS" | awk '{print $1}')
if [[ -z "$EXPECTED" ]]; then
  echo "Error: ${TARBALL} not found in SHA256SUMS" >&2
  exit 1
fi
ACTUAL=$(shasum -a 256 "$TMP/$TARBALL" | awk '{print $1}')
if [[ "$EXPECTED" != "$ACTUAL" ]]; then
  echo "Error: checksum mismatch" >&2
  echo "  expected: $EXPECTED" >&2
  echo "  actual:   $ACTUAL" >&2
  exit 1
fi
echo "[install] ✓ Checksum OK"

# ── extract ───────────────────────────────────────────────────────────────
INSTALL_DIR="$INSTALL_PREFIX/share/autonomos"
mkdir -p "$INSTALL_DIR"
echo "[install] Extracting to $INSTALL_DIR..."
tar -xzf "$TMP/$TARBALL" -C "$INSTALL_DIR"

# ── wrapper ───────────────────────────────────────────────────────────────
BIN_DIR="$INSTALL_PREFIX/bin"
WRAPPER="$BIN_DIR/autonomos"
mkdir -p "$BIN_DIR"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by autonomOS install.sh.
exec node "$INSTALL_DIR/index.js" "\$@"
EOF
chmod +x "$WRAPPER"
echo "[install] ✓ Wrote wrapper at $WRAPPER"

# ── PATH hint ─────────────────────────────────────────────────────────────
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    cat <<EOF

⚠️  $BIN_DIR is not on your PATH.
   Add this to your shell rc (~/.zshrc, ~/.bashrc, etc.):

     export PATH="$BIN_DIR:\$PATH"

EOF
    ;;
esac

# ── pm2 migration (if applicable) ─────────────────────────────────────────
# Existing users who installed via `make prod` typically have pm2 at one of:
#   $HOME/.bun/bin/pm2     (bun add -g pm2 — the existing Makefile install path)
#   $HOME/.local/bin/pm2
#   /usr/local/bin/pm2
#   /opt/homebrew/bin/pm2
# Walk all of them; default PATH alone misses bun-installed pm2 in
# non-interactive shells like `curl install.sh | bash`.
find_pm2() {
  if command -v pm2 >/dev/null 2>&1; then echo "pm2"; return 0; fi
  for p in "$HOME/.bun/bin/pm2" "$HOME/.local/bin/pm2" "$HOME/.volta/bin/pm2" \
           "/usr/local/bin/pm2" "/opt/homebrew/bin/pm2"; do
    [[ -x "$p" ]] && { echo "$p"; return 0; }
  done
  return 1
}

PM2_BIN="$(find_pm2 || true)"
PM2_MANAGED=0
if [[ -n "$PM2_BIN" ]] \
  && "$PM2_BIN" jlist 2>/dev/null | grep -q '"name":"autonomos"'; then
  PM2_MANAGED=1
fi

if [[ "${SKIP_INSTALL_SERVICE:-0}" != "1" ]]; then
  if [[ "$PM2_MANAGED" == "1" ]]; then
    echo "[install] Detected existing pm2-managed autonomos. Migrating..."
    "$WRAPPER" migrate-from-pm2
    echo "[install] ✓ Migration complete."
  else
    echo "[install] Running 'autonomos install-service'..."
    "$WRAPPER" install-service
  fi
fi

echo ""
echo "✓ autonomOS installed."
echo "  Binary:   $WRAPPER"
echo "  Bundle:   $INSTALL_DIR"
echo "  Run:      autonomos status"
