#!/usr/bin/env bash
# Supervise the from-source autonomos server via the OS-native init system
# (launchd on macOS, systemd-user on Linux) — Option B of the pm2 replacement.
#
# This replaces `pm2 start ecosystem.config.cjs`. It is invoked by `make prod`
# (locally and, via `make deploy`, on the remote). Design notes:
#
#  • SOURCE MODE: the supervised process runs the repo through `tsx`, not a
#    prebuilt bundle. `install-service`'s auto-detection can't express the tsx
#    loader (process.argv would be `node foo.ts`), so we generate a wrapper
#    script that re-establishes `tsx --env-file=.env` (exactly like `make dev`)
#    and point `install-service --bin=<wrapper>` at it.
#  • IDEMPOTENT: safe to re-run on every `make prod` / `make deploy`. First run
#    on a pm2 box migrates; later runs reinstall + restart so new source goes live.
#  • AUTO-MIGRATE: detects a pm2-managed autonomos and migrates it (preserving
#    PORT), unless NO_MIGRATE=1. install.sh does the same for curl installs.
#
# Env:
#   PORT          Port to supervise on (default 3100).
#   HOST          Interface to bind, baked into the service file as --host.
#                 Unset = the server's default: all interfaces (reachable over
#                 the network — how this is normally deployed). Set
#                 HOST=127.0.0.1 only to RESTRICT to loopback (a box reached
#                 exclusively via an SSH tunnel). For a persistent restriction
#                 prefer `AUTONOMOS_HOST=127.0.0.1` in this repo's .env: the
#                 wrapper below runs `tsx --env-file=<repo>/.env`, so it survives
#                 reinstalls that don't pass --host. Either way the auth token is
#                 required on API/WebSocket/MCP; POST /api/hooks/* and
#                 GET /api/host are not (yet) — a follow-up moves those onto a
#                 loopback-only listener.
#   NO_MIGRATE=1  Skip pm2 auto-migration (you take responsibility for pm2).
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PORT="${PORT:-3100}"
HOST="${HOST:-}"
TSX="$REPO/packages/server/node_modules/.bin/tsx"
CLI="$REPO/packages/cli/src/index.ts"
WRAPPER_DIR="$REPO/.autonomos-bin"
WRAPPER="$WRAPPER_DIR/autonomos"

# Rich PATH so the supervised daemon can resolve provider binaries (claude, etc.)
# in a non-login service environment. Mirrors the old ecosystem.config.cjs
# EXTRA_PATHS and providers/shared.ts BINARY_DIRS.
EXTRA_PATHS="$HOME/.local/bin:$HOME/.bun/bin:$HOME/.npm-global/bin:$HOME/.cargo/bin:$HOME/.volta/bin:/usr/local/bin:/opt/homebrew/bin:/snap/bin:/usr/bin:/bin"
export PATH="$EXTRA_PATHS:$PATH"

# systemd `--user` over a non-login ssh session (what `make deploy` uses) can't
# reach the user bus without XDG_RUNTIME_DIR — set it if absent (Linux only).
if [ "$(uname -s)" = "Linux" ] && [ -z "${XDG_RUNTIME_DIR:-}" ]; then
  export XDG_RUNTIME_DIR="/run/user/$(id -u)"
fi

if [ ! -x "$TSX" ]; then
  echo "✗ tsx not found at $TSX — run 'bun install' first" >&2
  exit 1
fi

# ── generate the source-runner wrapper the service supervises ────────────────
# tsx --env-file loads .env like `make dev`; the .env check is at runtime so a
# box that gains a .env later doesn't need the wrapper regenerated. "$@" passes
# the start subcommand + flags through.
mkdir -p "$WRAPPER_DIR"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install-prod-service.sh — runs autonomos from source.
ARGS=()
[ -f "$REPO/.env" ] && ARGS+=(--env-file="$REPO/.env")
exec "$TSX" "\${ARGS[@]}" "$CLI" "\$@"
EOF
chmod +x "$WRAPPER"

# Invoke the CLI through the wrapper so subcommands resolve the same way the
# supervised daemon will.
cli() { "$WRAPPER" "$@"; }

# ── detect an existing pm2-managed autonomos (mirrors install.sh) ────────────
find_pm2() {
  if command -v pm2 >/dev/null 2>&1; then echo "pm2"; return 0; fi
  for p in "$HOME/.bun/bin/pm2" "$HOME/.local/bin/pm2" "$HOME/.volta/bin/pm2" \
           "/usr/local/bin/pm2" "/opt/homebrew/bin/pm2"; do
    [ -x "$p" ] && { echo "$p"; return 0; }
  done
  return 1
}
pm2_manages_autonomos() {
  local bin; bin="$(find_pm2 || true)"
  # A transient jlist failure is treated as "pm2 doesn't manage autonomos" → we
  # take the fresh-install branch. Worst case is dual supervision (idempotent to
  # fix by re-running), never a down server.
  [ -n "$bin" ] && "$bin" jlist 2>/dev/null | grep -q '"name":"autonomos"'
}

# Only forward --host when the operator set HOST. Unset → the server's own
# loopback default applies. Deliberately unquoted below: empty expands to no
# argument at all, and a host is an IP/hostname (never contains spaces).
# Plain string rather than a bash array — macOS ships bash 3.2, where an empty
# array expansion under `set -u` is an "unbound variable" error.
HOST_ARG=""
if [ -n "$HOST" ]; then
  HOST_ARG="--host=$HOST"
  echo "[prod] Restricting bind to HOST=$HOST (overrides the all-interfaces default)."
fi

if [ "${NO_MIGRATE:-0}" != "1" ] && pm2_manages_autonomos; then
  echo ""
  echo "════════════════════════════════════════════════════════════════"
  echo "  Migrating autonomos from pm2 → OS-native supervision"
  echo "  (launchd/systemd-user). Stopping pm2, preserving PORT=$PORT."
  echo "  Set NO_MIGRATE=1 to skip this and manage pm2 yourself."
  echo "════════════════════════════════════════════════════════════════"
  echo ""
  # migrate-from-pm2 stops+deregisters pm2 then installs the service (it forwards
  # its whole argv to install-service, so --bin/--port/--host all carry through).
  # After it, the daemon is freshly running from source.
  # shellcheck disable=SC2086
  cli migrate-from-pm2 --bin="$WRAPPER" --port="$PORT" $HOST_ARG
else
  # Fresh box or already-native: (re)install the unit and restart so the latest
  # source is live (systemd `enable --now` won't restart an already-running unit,
  # so the explicit restart below is load-bearing on re-runs).
  # shellcheck disable=SC2086
  cli install-service --bin="$WRAPPER" --port="$PORT" $HOST_ARG --force
  cli restart
fi

# ── smoke: confirm the daemon actually came up ───────────────────────────────
echo ""
echo "[prod] Verifying the daemon is responsive..."
ok=0
for _ in $(seq 1 20); do
  if cli status >/dev/null 2>&1; then ok=1; break; fi
  sleep 0.5
done
cli status || true
if [ "$ok" != "1" ]; then
  echo "✗ Daemon did not become responsive. Check: autonomos logs" >&2
  exit 1
fi
echo "✓ autonomos is supervised by the OS and responding on port $PORT."
